[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "brine_wrapper"
version = "0.0.1"
dependencies = ["requests", "web3", "ecdsa"]

[project.optional-dependencies]
dev = ["pytest", "python-dotenv"]